{{- if empty .Values.database.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlas-api.db-secret" . }}
  labels:
    {{- include "atlas-api.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ default "" .Values.database.host | b64enc | quote }}
  databaseName: {{ default "" .Values.database.databaseName | b64enc | quote }}
  schemaName: {{ default "" .Values.database.schemaName | b64enc | quote }}
  username: {{ default "" .Values.database.username | b64enc | quote }}
  password: {{ default "" .Values.database.password | b64enc | quote }}

{{- end }}