name: Release Integration

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:

  deploy:
    name: Deploy
    uses: rerad-io/rerad-devops/.github/workflows/deploy-on-kuber.yaml@main
    with:
      runs-on: release-runner
      environment: production
      APP: atlas-api
      NAMESPACE: rerad-prod
    secrets:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      args: | 
        -f ./.helm/values.prod.yaml \
        --set image.tag=${{ github.sha }} \
        --set database.host=${{ secrets.POSTGRES_HOST }} \
        --set database.databaseName=${{ secrets.POSTGRES_NAME }} \
        --set database.password=${{ secrets.POSTGRES_PASSWORD }} \
        --wait